package com.codaily.auth.entity;

import com.codaily.project.entity.Project;
import com.codaily.project.entity.Specification;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;

import java.util.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;

    @Column(nullable = false, length = 20)
    private String socialProvider;

    @Column(nullable = true, length = 255)
    private String email;

    @Column(length = 255)
    private String socialId;

    @Column(nullable = false, length = 50)
    private String nickname;

    @Column(length = 255)
    private String password;

    @Column(length = 255)
    private String githubAccount;

    @Column(columnDefinition = "TEXT")
    private String githubProfileUrl;

    @Column(columnDefinition = "TEXT")
    private String githubAccessToken;

    private LocalDateTime tokenExpiredAt;

    @Column(columnDefinition = "TEXT")
    private String githubScope;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(columnDefinition = "TEXT")
    private String profileImage;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnore
    private List<Project> projects;

    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnore
    private List<TechStack> techStacks = new ArrayList<>();

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        if (this.role == null) {
            this.role = Role.USER;
        }
    }

    public enum Role {
        USER, ADMIN
    }

    @Transient
    public boolean needsGithubConnection() {
        return this.githubAccount == null || this.githubAccount.trim().isEmpty();
    }

    // 작성자: yeongenn - 최초 로그인인지 판별하는 메서드 (추가 정보 입력이 필요한지 확인)
    @Transient
    public boolean isFirstLogin() {
        // nickname이 자동생성된 형태([provider]_[랜덤문자열])이거나
        // githubAccount가 null이거나 비어있거나
        // profileImage가 null인 경우 최초 로그인으로 판단
        boolean hasAutoGeneratedNickname = this.nickname != null &&
                (this.nickname.startsWith("google_") || this.nickname.startsWith("naver_"));
        boolean hasNoGithubAccount = this.githubAccount == null || this.githubAccount.trim().isEmpty();
        boolean hasNoProfileImage = this.profileImage == null || this.profileImage.trim().isEmpty();

        return hasAutoGeneratedNickname || hasNoGithubAccount || hasNoProfileImage;
    }
}
