export const fetchedData = {
  "items": [
    {
      "date": "2025-08-15",
      "projectId": 3,
      "userId": 3,
      "triggerType": "AUTO",
      "contentMarkdown": "## 요약\n오늘은 두 주요 기능이 성공적으로 완료되었으며...",
      "summary": {
        "overall": "오늘의 진행상황은 전반적으로 안정적...",
        "strengths": "기능 안정성, 높은 품질지표, 꾸준한 커밋...",
        "improvements": "체크리스트 미완료 항목 해결, 코드 리뷰 활성화...",
        "risks": "체크리스트 미완료로 인한 품질 저하 가능성..."
      },
      "actionItems": null,
      "productivityMetrics": {
        "codeQuality": 88.75,
        "productivityScore": 90.5,
        "completedFeatures": 2,
        "totalCommits": 5
      },
      "completedFeatures": [
        {
          "featureId": 1001,
          "title": "상품 목록 조회 기능",
          "field": "상품 관리",
          "checklistCount": 2,
          "checklistDoneCount": 1,
          "codeQualityScore": 85.5,
          "summary": "성능 양호, 개선 여지 있음",
          "reviewIssues": [
            {
              "featureTitle": "상품 목록 조회 기능",
              "checklistItem": "상품 목록 API 연동",
              "category": "PERFORMANCE",
              "severity": "MEDIUM",
              "message": "N+1 쿼리 가능성",
              "filePath": "src/main/java/ProductService.java"
            }
          ]
        }
      ]
    },
    { "date": "2025-08-14", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n회고 시스템 개발...", "summary": { "overall": "회고 기능 구현 진행 중...", "strengths": "체계적인 분석, 사용자 친화적 인터페이스...", "improvements": "데이터 시각화 개선...", "risks": "성능 최적화 필요..." }, "actionItems": ["무한 스크롤 구현", "UI 개선"], "productivityMetrics": { "codeQuality": 89.2, "productivityScore": 85.3, "completedFeatures": 1, "totalCommits": 4 }, "completedFeatures": [{ "featureId": 1015, "title": "회고 시스템", "field": "프론트엔드", "checklistCount": 3, "checklistDoneCount": 2, "codeQualityScore": 89.2, "summary": "기본 구현 완료", "reviewIssues": [] }] },
    { "date": "2025-08-13", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n사용자 피드백 반영...", "summary": { "overall": "사용자 요구사항 분석 완료...", "strengths": "신속한 피드백 반영, 사용성 개선...", "improvements": "테스트 케이스 확대...", "risks": "기능 변경으로 인한 기존 코드 영향..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 91.7, "productivityScore": 88.9, "completedFeatures": 2, "totalCommits": 6 }, "completedFeatures": [{ "featureId": 1014, "title": "피드백 시스템", "field": "기획", "checklistCount": 4, "checklistDoneCount": 4, "codeQualityScore": 91.7, "summary": "피드백 반영 완료", "reviewIssues": [] }] },
    { "date": "2025-08-12", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n성능 모니터링 시스템 구축...", "summary": { "overall": "시스템 안정성 크게 향상...", "strengths": "실시간 모니터링, 알림 시스템...", "improvements": "대시보드 UI 개선...", "risks": "모니터링 데이터 저장 용량..." }, "actionItems": ["알림 설정 최적화"], "productivityMetrics": { "codeQuality": 93.4, "productivityScore": 92.1, "completedFeatures": 1, "totalCommits": 8 }, "completedFeatures": [{ "featureId": 1013, "title": "모니터링 시스템", "field": "DevOps", "checklistCount": 5, "checklistDoneCount": 5, "codeQualityScore": 93.4, "summary": "모니터링 구축 완료", "reviewIssues": [] }] },
    { "date": "2025-08-11", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n검색 기능 고도화...", "summary": { "overall": "검색 성능 대폭 개선...", "strengths": "빠른 검색 속도, 정확한 결과...", "improvements": "검색 필터 기능 추가...", "risks": "대용량 데이터 처리 시 지연..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 87.9, "productivityScore": 89.7, "completedFeatures": 2, "totalCommits": 7 }, "completedFeatures": [{ "featureId": 1012, "title": "고급 검색", "field": "백엔드", "checklistCount": 6, "checklistDoneCount": 5, "codeQualityScore": 87.9, "summary": "검색 기능 개선", "reviewIssues": [] }] },
    { "date": "2025-08-10", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n보안 강화 작업...", "summary": { "overall": "보안 수준 크게 향상...", "strengths": "취약점 패치, 암호화 강화...", "improvements": "보안 테스트 자동화...", "risks": "성능 영향 최소화 필요..." }, "actionItems": ["보안 감사 수행"], "productivityMetrics": { "codeQuality": 95.2, "productivityScore": 86.4, "completedFeatures": 1, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 1011, "title": "보안 강화", "field": "보안", "checklistCount": 7, "checklistDoneCount": 7, "codeQualityScore": 95.2, "summary": "보안 패치 완료", "reviewIssues": [] }] },
    { "date": "2025-08-09", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n데이터 분석 도구 개발...", "summary": { "overall": "분석 기능 구현 진행...", "strengths": "직관적인 차트, 상세한 통계...", "improvements": "실시간 업데이트 기능...", "risks": "데이터 처리 성능 최적화..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 90.1, "productivityScore": 91.3, "completedFeatures": 2, "totalCommits": 9 }, "completedFeatures": [{ "featureId": 1010, "title": "데이터 분석", "field": "데이터", "checklistCount": 4, "checklistDoneCount": 3, "codeQualityScore": 90.1, "summary": "분석 도구 구현", "reviewIssues": [] }] },
    { "date": "2025-08-08", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n알림 시스템 구현...", "summary": { "overall": "사용자 알림 기능 완성...", "strengths": "실시간 알림, 맞춤형 설정...", "improvements": "알림 그룹화 기능...", "risks": "과도한 알림으로 인한 사용자 피로..." }, "actionItems": ["알림 빈도 조절"], "productivityMetrics": { "codeQuality": 88.6, "productivityScore": 87.8, "completedFeatures": 1, "totalCommits": 5 }, "completedFeatures": [{ "featureId": 1009, "title": "알림 시스템", "field": "백엔드", "checklistCount": 3, "checklistDoneCount": 3, "codeQualityScore": 88.6, "summary": "알림 기능 완료", "reviewIssues": [] }] },
    { "date": "2025-08-07", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n파일 관리 시스템...", "summary": { "overall": "파일 업로드/다운로드 안정화...", "strengths": "빠른 처리 속도, 안전한 저장...", "improvements": "파일 미리보기 기능...", "risks": "저장 용량 관리 필요..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 92.8, "productivityScore": 90.2, "completedFeatures": 2, "totalCommits": 6 }, "completedFeatures": [{ "featureId": 1008, "title": "파일 관리", "field": "백엔드", "checklistCount": 5, "checklistDoneCount": 5, "codeQualityScore": 92.8, "summary": "파일 시스템 완료", "reviewIssues": [] }] },
    { "date": "2025-08-06", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n채팅 기능 고도화...", "summary": { "overall": "실시간 소통 기능 개선...", "strengths": "빠른 메시지 전송, 안정적 연결...", "improvements": "이미지 전송 기능...", "risks": "동시 접속자 증가 시 부하..." }, "actionItems": ["부하 테스트"], "productivityMetrics": { "codeQuality": 89.4, "productivityScore": 88.1, "completedFeatures": 1, "totalCommits": 7 }, "completedFeatures": [{ "featureId": 1007, "title": "채팅 고도화", "field": "프론트엔드", "checklistCount": 4, "checklistDoneCount": 4, "codeQualityScore": 89.4, "summary": "채팅 기능 개선", "reviewIssues": [] }] },
    { "date": "2025-08-05", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n권한 관리 시스템...", "summary": { "overall": "사용자 권한 체계 완성...", "strengths": "세분화된 권한, 보안 강화...", "improvements": "권한 설정 UI 개선...", "risks": "복잡한 권한 구조로 인한 혼란..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 94.1, "productivityScore": 85.9, "completedFeatures": 1, "totalCommits": 4 }, "completedFeatures": [{ "featureId": 1006, "title": "권한 관리", "field": "보안", "checklistCount": 6, "checklistDoneCount": 6, "codeQualityScore": 94.1, "summary": "권한 시스템 완료", "reviewIssues": [] }] },
    { "date": "2025-08-04", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n프로필 관리 기능...", "summary": { "overall": "사용자 프로필 기능 완성...", "strengths": "직관적인 설정, 개인화 옵션...", "improvements": "프로필 이미지 최적화...", "risks": "개인정보 보안 강화 필요..." }, "actionItems": ["개인정보 암호화"], "productivityMetrics": { "codeQuality": 87.3, "productivityScore": 89.5, "completedFeatures": 2, "totalCommits": 8 }, "completedFeatures": [{ "featureId": 1005, "title": "프로필 관리", "field": "프론트엔드", "checklistCount": 3, "checklistDoneCount": 3, "codeQualityScore": 87.3, "summary": "프로필 기능 완료", "reviewIssues": [] }] },
    { "date": "2025-08-03", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n코드 리뷰 시스템...", "summary": { "overall": "코드 품질 관리 체계 구축...", "strengths": "자동화된 리뷰, 품질 지표...", "improvements": "리뷰 속도 개선...", "risks": "리뷰어 부족으로 인한 지연..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 96.7, "productivityScore": 92.4, "completedFeatures": 1, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 1004, "title": "코드 리뷰", "field": "DevOps", "checklistCount": 5, "checklistDoneCount": 5, "codeQualityScore": 96.7, "summary": "리뷰 시스템 완료", "reviewIssues": [] }] },
    { "date": "2025-08-02", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n테스트 자동화 구축...", "summary": { "overall": "테스트 커버리지 대폭 증가...", "strengths": "자동화된 테스트, 빠른 피드백...", "improvements": "E2E 테스트 확대...", "risks": "테스트 유지보수 비용..." }, "actionItems": ["테스트 문서화"], "productivityMetrics": { "codeQuality": 93.9, "productivityScore": 91.7, "completedFeatures": 2, "totalCommits": 10 }, "completedFeatures": [{ "featureId": 1003, "title": "테스트 자동화", "field": "QA", "checklistCount": 7, "checklistDoneCount": 6, "codeQualityScore": 93.9, "summary": "자동화 테스트 구축", "reviewIssues": [] }] },
    { "date": "2025-08-01", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\nAPI 성능 최적화...", "summary": { "overall": "API 응답 속도 크게 개선...", "strengths": "캐싱 적용, 쿼리 최적화...", "improvements": "더 많은 엔드포인트 최적화...", "risks": "캐시 무효화 전략 필요..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 91.2, "productivityScore": 88.6, "completedFeatures": 1, "totalCommits": 5 }, "completedFeatures": [{ "featureId": 1002, "title": "API 최적화", "field": "백엔드", "checklistCount": 4, "checklistDoneCount": 4, "codeQualityScore": 91.2, "summary": "성능 최적화 완료", "reviewIssues": [] }] }
  ],
  "hasNext": true,
  "nextBefore": "2025-07-31"
}

export const fetchedData2 = {
  "items": [
    { "date": "2025-07-31", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n프로젝트 초기 설정...", "summary": { "overall": "개발 환경 구축 완료...", "strengths": "체계적인 설정, 명확한 가이드라인...", "improvements": "문서화 보완...", "risks": "초기 설정 변경 리스크..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 85.4, "productivityScore": 78.9, "completedFeatures": 1, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 2001, "title": "개발 환경 설정", "field": "설정", "checklistCount": 8, "checklistDoneCount": 7, "codeQualityScore": 85.4, "summary": "환경 설정 완료", "reviewIssues": [] }] },
    { "date": "2025-07-30", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n데이터베이스 설계...", "summary": { "overall": "DB 스키마 설계 완료...", "strengths": "정규화 완료, 성능 고려...", "improvements": "인덱스 최적화...", "risks": "스키마 변경 비용..." }, "actionItems": ["인덱스 검토"], "productivityMetrics": { "codeQuality": 92.1, "productivityScore": 83.7, "completedFeatures": 1, "totalCommits": 4 }, "completedFeatures": [{ "featureId": 2002, "title": "DB 설계", "field": "데이터베이스", "checklistCount": 6, "checklistDoneCount": 6, "codeQualityScore": 92.1, "summary": "DB 설계 완료", "reviewIssues": [] }] },
    { "date": "2025-07-29", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n로그인 시스템 구현...", "summary": { "overall": "사용자 인증 기능 완성...", "strengths": "보안 강화, 사용자 편의성...", "improvements": "소셜 로그인 추가...", "risks": "보안 취약점 점검 필요..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 89.8, "productivityScore": 86.2, "completedFeatures": 2, "totalCommits": 7 }, "completedFeatures": [{ "featureId": 2003, "title": "로그인 시스템", "field": "인증", "checklistCount": 5, "checklistDoneCount": 5, "codeQualityScore": 89.8, "summary": "인증 시스템 완료", "reviewIssues": [] }] },
    { "date": "2025-07-28", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n메인 페이지 구현...", "summary": { "overall": "메인 화면 기본 기능 완성...", "strengths": "직관적인 UI, 빠른 로딩...", "improvements": "반응형 디자인 개선...", "risks": "브라우저 호환성..." }, "actionItems": ["크로스 브라우징 테스트"], "productivityMetrics": { "codeQuality": 87.5, "productivityScore": 89.1, "completedFeatures": 1, "totalCommits": 6 }, "completedFeatures": [{ "featureId": 2004, "title": "메인 페이지", "field": "프론트엔드", "checklistCount": 4, "checklistDoneCount": 4, "codeQualityScore": 87.5, "summary": "메인 화면 완료", "reviewIssues": [] }] },
    { "date": "2025-07-27", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n네비게이션 구현...", "summary": { "overall": "사이트 네비게이션 완성...", "strengths": "사용자 친화적, 직관적 구조...", "improvements": "모바일 메뉴 개선...", "risks": "메뉴 구조 변경 시 혼란..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 90.3, "productivityScore": 87.9, "completedFeatures": 1, "totalCommits": 5 }, "completedFeatures": [{ "featureId": 2005, "title": "네비게이션", "field": "UI/UX", "checklistCount": 3, "checklistDoneCount": 3, "codeQualityScore": 90.3, "summary": "네비게이션 완료", "reviewIssues": [] }] },
    { "date": "2025-07-26", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n기본 레이아웃 구성...", "summary": { "overall": "전체 레이아웃 구조 완성...", "strengths": "일관된 디자인, 확장 가능성...", "improvements": "컴포넌트 재사용성 개선...", "risks": "레이아웃 변경 시 전체 영향..." }, "actionItems": ["컴포넌트 분리"], "productivityMetrics": { "codeQuality": 88.7, "productivityScore": 85.4, "completedFeatures": 2, "totalCommits": 8 }, "completedFeatures": [{ "featureId": 2006, "title": "기본 레이아웃", "field": "프론트엔드", "checklistCount": 5, "checklistDoneCount": 4, "codeQualityScore": 88.7, "summary": "레이아웃 구성 완료", "reviewIssues": [] }] },
    { "date": "2025-07-25", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n상태 관리 설정...", "summary": { "overall": "전역 상태 관리 체계 구축...", "strengths": "효율적인 상태 관리, 예측 가능한 업데이트...", "improvements": "상태 최적화...", "risks": "복잡한 상태 구조로 인한 디버깅 어려움..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 93.2, "productivityScore": 88.8, "completedFeatures": 1, "totalCommits": 4 }, "completedFeatures": [{ "featureId": 2007, "title": "상태 관리", "field": "아키텍처", "checklistCount": 6, "checklistDoneCount": 6, "codeQualityScore": 93.2, "summary": "상태 관리 설정 완료", "reviewIssues": [] }] },
    { "date": "2025-07-24", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n라우팅 설정...", "summary": { "overall": "페이지 라우팅 구조 완성...", "strengths": "명확한 URL 구조, SEO 친화적...", "improvements": "동적 라우팅 확장...", "risks": "라우팅 변경 시 기존 링크 무효화..." }, "actionItems": ["라우팅 문서화"], "productivityMetrics": { "codeQuality": 91.6, "productivityScore": 84.3, "completedFeatures": 1, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 2008, "title": "라우팅 설정", "field": "프론트엔드", "checklistCount": 4, "checklistDoneCount": 4, "codeQualityScore": 91.6, "summary": "라우팅 완료", "reviewIssues": [] }] },
    { "date": "2025-07-23", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n컴포넌트 라이브러리 구축...", "summary": { "overall": "재사용 가능한 컴포넌트 완성...", "strengths": "일관된 디자인, 높은 재사용성...", "improvements": "컴포넌트 문서화...", "risks": "컴포넌트 변경 시 전체 영향..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 89.4, "productivityScore": 90.7, "completedFeatures": 2, "totalCommits": 9 }, "completedFeatures": [{ "featureId": 2009, "title": "컴포넌트 라이브러리", "field": "UI/UX", "checklistCount": 7, "checklistDoneCount": 6, "codeQualityScore": 89.4, "summary": "컴포넌트 구축", "reviewIssues": [] }] },
    { "date": "2025-07-22", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\nAPI 클라이언트 설정...", "summary": { "overall": "서버 통신 기반 구축...", "strengths": "효율적인 HTTP 클라이언트, 에러 핸들링...", "improvements": "재시도 로직 개선...", "risks": "네트워크 오류 처리..." }, "actionItems": ["에러 핸들링 강화"], "productivityMetrics": { "codeQuality": 92.8, "productivityScore": 86.1, "completedFeatures": 1, "totalCommits": 5 }, "completedFeatures": [{ "featureId": 2010, "title": "API 클라이언트", "field": "통신", "checklistCount": 5, "checklistDoneCount": 5, "codeQualityScore": 92.8, "summary": "API 설정 완료", "reviewIssues": [] }] },
    { "date": "2025-07-21", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n스타일링 시스템 구축...", "summary": { "overall": "디자인 시스템 기반 마련...", "strengths": "일관된 스타일, 유지보수성...", "improvements": "테마 시스템 추가...", "risks": "스타일 변경 시 전체 영향..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 88.1, "productivityScore": 87.5, "completedFeatures": 1, "totalCommits": 6 }, "completedFeatures": [{ "featureId": 2011, "title": "스타일링 시스템", "field": "디자인", "checklistCount": 4, "checklistDoneCount": 4, "codeQualityScore": 88.1, "summary": "스타일 시스템 완료", "reviewIssues": [] }] },
    { "date": "2025-07-20", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n폼 검증 시스템...", "summary": { "overall": "사용자 입력 검증 체계 구축...", "strengths": "실시간 검증, 친화적 에러 메시지...", "improvements": "검증 규칙 확장...", "risks": "과도한 검증으로 인한 사용성 저하..." }, "actionItems": ["검증 규칙 최적화"], "productivityMetrics": { "codeQuality": 90.7, "productivityScore": 89.3, "completedFeatures": 2, "totalCommits": 7 }, "completedFeatures": [{ "featureId": 2012, "title": "폼 검증", "field": "프론트엔드", "checklistCount": 6, "checklistDoneCount": 5, "codeQualityScore": 90.7, "summary": "폼 검증 구현", "reviewIssues": [] }] },
    { "date": "2025-07-19", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n국제화 설정...", "summary": { "overall": "다국어 지원 기반 마련...", "strengths": "확장 가능한 구조, 사용자 편의성...", "improvements": "번역 품질 개선...", "risks": "번역 유지보수 비용..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 87.9, "productivityScore": 82.6, "completedFeatures": 1, "totalCommits": 4 }, "completedFeatures": [{ "featureId": 2013, "title": "국제화", "field": "현지화", "checklistCount": 5, "checklistDoneCount": 5, "codeQualityScore": 87.9, "summary": "다국어 설정 완료", "reviewIssues": [] }] },
    { "date": "2025-07-18", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n접근성 개선...", "summary": { "overall": "웹 접근성 기준 충족...", "strengths": "스크린 리더 지원, 키보드 네비게이션...", "improvements": "색상 대비 개선...", "risks": "접근성 요구사항 변경..." }, "actionItems": ["접근성 테스트"], "productivityMetrics": { "codeQuality": 91.3, "productivityScore": 85.8, "completedFeatures": 1, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 2014, "title": "접근성 개선", "field": "UI/UX", "checklistCount": 7, "checklistDoneCount": 6, "codeQualityScore": 91.3, "summary": "접근성 기준 충족", "reviewIssues": [] }] },
    { "date": "2025-07-17", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n성능 최적화 기반...", "summary": { "overall": "애플리케이션 성능 기반 마련...", "strengths": "번들 최적화, 지연 로딩...", "improvements": "이미지 최적화...", "risks": "최적화로 인한 복잡성 증가..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 94.5, "productivityScore": 88.2, "completedFeatures": 2, "totalCommits": 8 }, "completedFeatures": [{ "featureId": 2015, "title": "성능 최적화", "field": "성능", "checklistCount": 6, "checklistDoneCount": 6, "codeQualityScore": 94.5, "summary": "성능 기반 마련", "reviewIssues": [] }] }
  ],
  "hasNext": true,
  "nextBefore": "2025-07-16"
}

export const fetchedData3 = {
  "items": [
    { "date": "2025-07-16", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n코드 품질 도구 설정...", "summary": { "overall": "코드 품질 관리 체계 구축...", "strengths": "자동화된 검사, 일관된 코딩 스타일...", "improvements": "규칙 세부 조정...", "risks": "과도한 규칙으로 인한 개발 속도 저하..." }, "actionItems": ["린트 규칙 최적화"], "productivityMetrics": { "codeQuality": 96.2, "productivityScore": 84.7, "completedFeatures": 1, "totalCommits": 2 }, "completedFeatures": [{ "featureId": 3001, "title": "코드 품질 도구", "field": "개발도구", "checklistCount": 4, "checklistDoneCount": 4, "codeQualityScore": 96.2, "summary": "품질 도구 설정 완료", "reviewIssues": [] }] },
    { "date": "2025-07-15", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n버전 관리 설정...", "summary": { "overall": "Git 워크플로우 구축...", "strengths": "체계적인 브랜치 관리, 명확한 커밋 규칙...", "improvements": "자동화된 배포 파이프라인...", "risks": "복잡한 머지 충돌..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 89.8, "productivityScore": 91.4, "completedFeatures": 1, "totalCommits": 5 }, "completedFeatures": [{ "featureId": 3002, "title": "버전 관리", "field": "DevOps", "checklistCount": 3, "checklistDoneCount": 3, "codeQualityScore": 89.8, "summary": "Git 워크플로우 완료", "reviewIssues": [] }] },
    { "date": "2025-07-14", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n배포 환경 구축...", "summary": { "overall": "개발/스테이징/프로덕션 환경 분리...", "strengths": "안정적인 배포 프로세스, 환경별 설정 관리...", "improvements": "모니터링 강화...", "risks": "환경 간 설정 불일치..." }, "actionItems": ["환경 설정 검증"], "productivityMetrics": { "codeQuality": 92.6, "productivityScore": 87.9, "completedFeatures": 2, "totalCommits": 6 }, "completedFeatures": [{ "featureId": 3003, "title": "배포 환경", "field": "인프라", "checklistCount": 8, "checklistDoneCount": 7, "codeQualityScore": 92.6, "summary": "배포 환경 구축", "reviewIssues": [] }] },
    { "date": "2025-07-13", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n문서화 시스템...", "summary": { "overall": "프로젝트 문서화 체계 완성...", "strengths": "자동화된 API 문서, 개발 가이드...", "improvements": "예제 코드 확충...", "risks": "문서 업데이트 누락..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 88.4, "productivityScore": 89.7, "completedFeatures": 1, "totalCommits": 4 }, "completedFeatures": [{ "featureId": 3004, "title": "문서화 시스템", "field": "문서", "checklistCount": 5, "checklistDoneCount": 5, "codeQualityScore": 88.4, "summary": "문서화 완료", "reviewIssues": [] }] },
    { "date": "2025-07-12", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n백업 시스템 구축...", "summary": { "overall": "데이터 백업 및 복구 체계 마련...", "strengths": "자동화된 백업, 빠른 복구...", "improvements": "백업 검증 자동화...", "risks": "백업 데이터 손상..." }, "actionItems": ["백업 검증 스크립트"], "productivityMetrics": { "codeQuality": 94.3, "productivityScore": 86.2, "completedFeatures": 1, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 3005, "title": "백업 시스템", "field": "인프라", "checklistCount": 6, "checklistDoneCount": 6, "codeQualityScore": 94.3, "summary": "백업 시스템 완료", "reviewIssues": [] }] },
    { "date": "2025-07-11", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n보안 정책 수립...", "summary": { "overall": "애플리케이션 보안 기준 정립...", "strengths": "포괄적인 보안 정책, 정기적인 감사...", "improvements": "보안 교육 확대...", "risks": "신규 보안 위협 대응..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 97.1, "productivityScore": 83.5, "completedFeatures": 1, "totalCommits": 2 }, "completedFeatures": [{ "featureId": 3006, "title": "보안 정책", "field": "보안", "checklistCount": 9, "checklistDoneCount": 9, "codeQualityScore": 97.1, "summary": "보안 정책 완료", "reviewIssues": [] }] },
    { "date": "2025-07-10", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n에러 로깅 시스템...", "summary": { "overall": "종합적인 에러 추적 및 분석 체계...", "strengths": "실시간 알림, 상세한 로그 분석...", "improvements": "에러 패턴 분석 자동화...", "risks": "로그 데이터 과부하..." }, "actionItems": ["로그 보관 정책 수립"], "productivityMetrics": { "codeQuality": 91.7, "productivityScore": 88.9, "completedFeatures": 2, "totalCommits": 7 }, "completedFeatures": [{ "featureId": 3007, "title": "에러 로깅", "field": "모니터링", "checklistCount": 5, "checklistDoneCount": 4, "codeQualityScore": 91.7, "summary": "로깅 시스템 구축", "reviewIssues": [] }] },
    { "date": "2025-07-09", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n캐싱 전략 구현...", "summary": { "overall": "다층 캐싱 시스템 구축...", "strengths": "응답 속도 향상, 서버 부하 감소...", "improvements": "캐시 무효화 정책 개선...", "risks": "캐시 일관성 문제..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 93.8, "productivityScore": 90.1, "completedFeatures": 1, "totalCommits": 5 }, "completedFeatures": [{ "featureId": 3008, "title": "캐싱 시스템", "field": "성능", "checklistCount": 7, "checklistDoneCount": 7, "codeQualityScore": 93.8, "summary": "캐싱 전략 완료", "reviewIssues": [] }] },
    { "date": "2025-07-08", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n부하 테스트 환경...", "summary": { "overall": "성능 테스트 인프라 구축...", "strengths": "자동화된 부하 테스트, 성능 지표 수집...", "improvements": "시나리오 다양화...", "risks": "테스트 환경과 실제 환경 차이..." }, "actionItems": ["실제 트래픽 패턴 분석"], "productivityMetrics": { "codeQuality": 89.2, "productivityScore": 87.6, "completedFeatures": 1, "totalCommits": 4 }, "completedFeatures": [{ "featureId": 3009, "title": "부하 테스트", "field": "QA", "checklistCount": 6, "checklistDoneCount": 5, "codeQualityScore": 89.2, "summary": "부하 테스트 환경 구축", "reviewIssues": [] }] },
    { "date": "2025-07-07", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\nCDN 설정 및 최적화...", "summary": { "overall": "전역 콘텐츠 배포 네트워크 구축...", "strengths": "빠른 콘텐츠 로딩, 글로벌 접근성...", "improvements": "캐시 정책 세밀 조정...", "risks": "CDN 서비스 의존성..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 90.5, "productivityScore": 91.3, "completedFeatures": 2, "totalCommits": 6 }, "completedFeatures": [{ "featureId": 3010, "title": "CDN 최적화", "field": "인프라", "checklistCount": 4, "checklistDoneCount": 4, "codeQualityScore": 90.5, "summary": "CDN 설정 완료", "reviewIssues": [] }] },
    { "date": "2025-07-06", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n소셜 로그인 통합...", "summary": { "overall": "다양한 OAuth 제공자 연동...", "strengths": "사용자 편의성 증대, 보안 강화...", "improvements": "추가 제공자 연동...", "risks": "외부 서비스 의존성..." }, "actionItems": ["추가 OAuth 제공자 검토"], "productivityMetrics": { "codeQuality": 88.9, "productivityScore": 89.4, "completedFeatures": 1, "totalCommits": 8 }, "completedFeatures": [{ "featureId": 3011, "title": "소셜 로그인", "field": "인증", "checklistCount": 5, "checklistDoneCount": 4, "codeQualityScore": 88.9, "summary": "소셜 로그인 구현", "reviewIssues": [] }] },
    { "date": "2025-07-05", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n실시간 통신 기반...", "summary": { "overall": "WebSocket 기반 실시간 기능...", "strengths": "즉시성, 사용자 경험 향상...", "improvements": "연결 안정성 개선...", "risks": "연결 끊김 처리..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 92.1, "productivityScore": 88.7, "completedFeatures": 1, "totalCommits": 9 }, "completedFeatures": [{ "featureId": 3012, "title": "실시간 통신", "field": "통신", "checklistCount": 6, "checklistDoneCount": 6, "codeQualityScore": 92.1, "summary": "실시간 기능 구현", "reviewIssues": [] }] },
    { "date": "2025-07-04", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n이메일 시스템 구축...", "summary": { "overall": "자동화된 이메일 발송 시스템...", "strengths": "템플릿 기반 발송, 발송 이력 관리...", "improvements": "개인화 기능 강화...", "risks": "스팸 필터링 이슈..." }, "actionItems": ["이메일 템플릿 개선"], "productivityMetrics": { "codeQuality": 87.6, "productivityScore": 86.8, "completedFeatures": 2, "totalCommits": 5 }, "completedFeatures": [{ "featureId": 3013, "title": "이메일 시스템", "field": "통신", "checklistCount": 7, "checklistDoneCount": 6, "codeQualityScore": 87.6, "summary": "이메일 시스템 구축", "reviewIssues": [] }] },
    { "date": "2025-07-03", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n검색 엔진 최적화...", "summary": { "overall": "SEO 기본 설정 및 최적화...", "strengths": "메타 태그 최적화, 사이트맵 생성...", "improvements": "구조화된 데이터 추가...", "risks": "검색 엔진 알고리즘 변경..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 85.3, "productivityScore": 83.9, "completedFeatures": 1, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 3014, "title": "SEO 최적화", "field": "마케팅", "checklistCount": 8, "checklistDoneCount": 7, "codeQualityScore": 85.3, "summary": "SEO 기본 설정 완료", "reviewIssues": [] }] },
    { "date": "2025-07-02", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n분석 도구 통합...", "summary": { "overall": "사용자 행동 분석 시스템...", "strengths": "상세한 사용자 추적, 인사이트 도출...", "improvements": "실시간 분석 대시보드...", "risks": "개인정보 보호 규정 준수..." }, "actionItems": ["개인정보 처리방침 업데이트"], "productivityMetrics": { "codeQuality": 91.4, "productivityScore": 89.2, "completedFeatures": 1, "totalCommits": 7 }, "completedFeatures": [{ "featureId": 3015, "title": "분석 도구", "field": "분석", "checklistCount": 5, "checklistDoneCount": 5, "codeQualityScore": 91.4, "summary": "분석 시스템 통합", "reviewIssues": [] }] }
  ],
  "hasNext": true,
  "nextBefore": "2025-07-01"
}

export const fetchedData4 = {
  "items": [
    { "date": "2025-07-01", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n최종 배포 준비...", "summary": { "overall": "프로덕션 배포를 위한 최종 점검...", "strengths": "안정적인 시스템, 완전한 기능 구현...", "improvements": "성능 미세 조정...", "risks": "초기 사용자 피드백 대응..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 96.8, "productivityScore": 94.2, "completedFeatures": 1, "totalCommits": 2 }, "completedFeatures": [{ "featureId": 4001, "title": "배포 준비", "field": "배포", "checklistCount": 10, "checklistDoneCount": 10, "codeQualityScore": 96.8, "summary": "배포 준비 완료", "reviewIssues": [] }] },
    { "date": "2025-06-30", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n사용자 가이드 작성...", "summary": { "overall": "최종 사용자를 위한 가이드 문서...", "strengths": "직관적인 설명, 단계별 안내...", "improvements": "비디오 튜토리얼 추가...", "risks": "사용자 이해도 차이..." }, "actionItems": ["사용자 테스트 진행"], "productivityMetrics": { "codeQuality": 88.1, "productivityScore": 85.6, "completedFeatures": 1, "totalCommits": 4 }, "completedFeatures": [{ "featureId": 4002, "title": "사용자 가이드", "field": "문서", "checklistCount": 6, "checklistDoneCount": 5, "codeQualityScore": 88.1, "summary": "가이드 문서 작성", "reviewIssues": [] }] },
    { "date": "2025-06-29", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n최종 테스트 완료...", "summary": { "overall": "모든 기능에 대한 종합 테스트...", "strengths": "높은 테스트 커버리지, 안정성 확보...", "improvements": "자동화 테스트 확대...", "risks": "실제 환경에서의 예상치 못한 이슈..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 97.3, "productivityScore": 93.8, "completedFeatures": 2, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 4003, "title": "최종 테스트", "field": "QA", "checklistCount": 12, "checklistDoneCount": 12, "codeQualityScore": 97.3, "summary": "종합 테스트 완료", "reviewIssues": [] }] },
    { "date": "2025-06-28", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n보안 감사 완료...", "summary": { "overall": "전체 시스템 보안 점검...", "strengths": "취약점 제로, 강화된 보안...", "improvements": "지속적 보안 모니터링...", "risks": "신규 보안 위협 등장..." }, "actionItems": ["보안 모니터링 설정"], "productivityMetrics": { "codeQuality": 98.1, "productivityScore": 91.4, "completedFeatures": 1, "totalCommits": 1 }, "completedFeatures": [{ "featureId": 4004, "title": "보안 감사", "field": "보안", "checklistCount": 15, "checklistDoneCount": 15, "codeQualityScore": 98.1, "summary": "보안 감사 통과", "reviewIssues": [] }] },
    { "date": "2025-06-27", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n성능 최종 최적화...", "summary": { "overall": "시스템 성능 최종 튜닝...", "strengths": "최적의 응답 속도, 효율적 자원 사용...", "improvements": "지속적 성능 모니터링...", "risks": "사용자 증가 시 부하..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 95.7, "productivityScore": 96.1, "completedFeatures": 1, "totalCommits": 5 }, "completedFeatures": [{ "featureId": 4005, "title": "성능 최적화", "field": "성능", "checklistCount": 8, "checklistDoneCount": 8, "codeQualityScore": 95.7, "summary": "성능 최적화 완료", "reviewIssues": [] }] },
    { "date": "2025-06-26", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n운영 매뉴얼 완성...", "summary": { "overall": "시스템 운영을 위한 가이드...", "strengths": "상세한 운영 절차, 문제 해결 가이드...", "improvements": "운영 자동화 확대...", "risks": "운영 담당자 교체 시 인수인계..." }, "actionItems": ["운영 교육 진행"], "productivityMetrics": { "codeQuality": 89.6, "productivityScore": 87.2, "completedFeatures": 1, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 4006, "title": "운영 매뉴얼", "field": "운영", "checklistCount": 9, "checklistDoneCount": 9, "codeQualityScore": 89.6, "summary": "운영 매뉴얼 완성", "reviewIssues": [] }] },
    { "date": "2025-06-25", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n장애 대응 체계...", "summary": { "overall": "장애 발생 시 대응 프로세스...", "strengths": "신속한 대응 체계, 명확한 역할 분담...", "improvements": "예방적 모니터링 강화...", "risks": "예상치 못한 장애 유형..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 92.4, "productivityScore": 88.9, "completedFeatures": 1, "totalCommits": 4 }, "completedFeatures": [{ "featureId": 4007, "title": "장애 대응", "field": "운영", "checklistCount": 7, "checklistDoneCount": 7, "codeQualityScore": 92.4, "summary": "장애 대응 체계 완성", "reviewIssues": [] }] },
    { "date": "2025-06-24", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n모니터링 대시보드...", "summary": { "overall": "실시간 시스템 상태 모니터링...", "strengths": "직관적인 대시보드, 실시간 알림...", "improvements": "예측 분석 기능...", "risks": "모니터링 데이터 과부하..." }, "actionItems": ["알림 임계값 조정"], "productivityMetrics": { "codeQuality": 93.1, "productivityScore": 90.5, "completedFeatures": 2, "totalCommits": 6 }, "completedFeatures": [{ "featureId": 4008, "title": "모니터링 대시보드", "field": "모니터링", "checklistCount": 6, "checklistDoneCount": 6, "codeQualityScore": 93.1, "summary": "대시보드 구축 완료", "reviewIssues": [] }] },
    { "date": "2025-06-23", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n데이터 마이그레이션...", "summary": { "overall": "기존 데이터 신규 시스템 이관...", "strengths": "무손실 데이터 이관, 검증 완료...", "improvements": "이관 속도 최적화...", "risks": "대용량 데이터 처리 시간..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 94.8, "productivityScore": 89.3, "completedFeatures": 1, "totalCommits": 7 }, "completedFeatures": [{ "featureId": 4009, "title": "데이터 마이그레이션", "field": "데이터", "checklistCount": 11, "checklistDoneCount": 11, "codeQualityScore": 94.8, "summary": "데이터 이관 완료", "reviewIssues": [] }] },
    { "date": "2025-06-22", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n사용자 교육 자료...", "summary": { "overall": "새로운 기능 사용법 교육...", "strengths": "단계별 학습 과정, 실습 예제...", "improvements": "인터랙티브 튜토리얼...", "risks": "사용자 학습 부담..." }, "actionItems": ["피드백 수집"], "productivityMetrics": { "codeQuality": 86.7, "productivityScore": 84.1, "completedFeatures": 1, "totalCommits": 2 }, "completedFeatures": [{ "featureId": 4010, "title": "사용자 교육", "field": "교육", "checklistCount": 5, "checklistDoneCount": 4, "codeQualityScore": 86.7, "summary": "교육 자료 준비", "reviewIssues": [] }] },
    { "date": "2025-06-21", "projectId": 3, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n라이선스 정리...", "summary": { "overall": "사용된 라이브러리 라이선스 검토...", "strengths": "법적 리스크 제거, 명확한 라이선스 관리...", "improvements": "자동화된 라이선스 검사...", "risks": "라이선스 변경 사항..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 91.2, "productivityScore": 82.7, "completedFeatures": 1, "totalCommits": 1 }, "completedFeatures": [{ "featureId": 4011, "title": "라이선스 관리", "field": "법무", "checklistCount": 4, "checklistDoneCount": 4, "codeQualityScore": 91.2, "summary": "라이선스 정리 완료", "reviewIssues": [] }] },
    { "date": "2025-06-20", "projectId": 5, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n접근성 최종 검증...", "summary": { "overall": "웹 접근성 표준 준수 확인...", "strengths": "WCAG 기준 충족, 다양한 사용자 지원...", "improvements": "접근성 자동 테스트...", "risks": "접근성 기준 변경..." }, "actionItems": ["접근성 인증 신청"], "productivityMetrics": { "codeQuality": 95.4, "productivityScore": 88.6, "completedFeatures": 1, "totalCommits": 3 }, "completedFeatures": [{ "featureId": 4012, "title": "접근성 검증", "field": "접근성", "checklistCount": 13, "checklistDoneCount": 13, "codeQualityScore": 95.4, "summary": "접근성 기준 충족", "reviewIssues": [] }] },
    { "date": "2025-06-19", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n국제화 완성...", "summary": { "overall": "다국어 지원 최종 완성...", "strengths": "완전한 번역, 현지화 적용...", "improvements": "번역 품질 관리 자동화...", "risks": "지역별 문화적 차이..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 90.8, "productivityScore": 87.4, "completedFeatures": 2, "totalCommits": 5 }, "completedFeatures": [{ "featureId": 4013, "title": "국제화 완성", "field": "현지화", "checklistCount": 8, "checklistDoneCount": 8, "codeQualityScore": 90.8, "summary": "다국어 지원 완료", "reviewIssues": [] }] },
    { "date": "2025-06-18", "projectId": 5, "userId": 3, "triggerType": "MANUAL", "contentMarkdown": "## 요약\n품질 보증 완료...", "summary": { "overall": "전체 시스템 품질 최종 확인...", "strengths": "높은 품질 지표, 안정성 확보...", "improvements": "지속적 품질 관리...", "risks": "품질 기준 변경..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 98.6, "productivityScore": 95.2, "completedFeatures": 1, "totalCommits": 2 }, "completedFeatures": [{ "featureId": 4014, "title": "품질 보증", "field": "QA", "checklistCount": 16, "checklistDoneCount": 16, "codeQualityScore": 98.6, "summary": "품질 보증 완료", "reviewIssues": [] }] },
    { "date": "2025-06-17", "projectId": 3, "userId": 3, "triggerType": "AUTO", "contentMarkdown": "## 요약\n프로젝트 완료...", "summary": { "overall": "전체 프로젝트 개발 완료...", "strengths": "목표 달성, 높은 품질, 사용자 만족...", "improvements": "지속적 개선 계획...", "risks": "운영 단계에서의 새로운 요구사항..." }, "actionItems": null, "productivityMetrics": { "codeQuality": 97.9, "productivityScore": 96.8, "completedFeatures": 3, "totalCommits": 1 }, "completedFeatures": [{ "featureId": 4015, "title": "프로젝트 완료", "field": "완료", "checklistCount": 20, "checklistDoneCount": 20, "codeQualityScore": 97.9, "summary": "프로젝트 성공적 완료", "reviewIssues": [] }] }
  ],
  "hasNext": false,
  "nextBefore": null
}