spring:
  application:
    name: Codaily

  config:
    import:
      - classpath:application-secret.yml

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          #          github:
          #            client-id: ${GITHUB.CLIENT_ID}
          #            client-secret: ${GITHUB.CLIENT_SECRET}
          #            redirect-uri: http://localhost:8080/oauth/github/callback
          #            token-uri: https://github.com/login/oauth/access_token
          #            user-uri: https://api.github.com/user
          google:
            client-id: ${GOOGLE.CLIENT_ID}
            client-secret: ${GOOGLE.CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          naver:
            client-id: ${NAVER.CLIENT_ID}
            client-secret: ${NAVER.CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

github:
  client-id: ${GITHUB.CLIENT_ID}
  client-secret: ${GITHUB.CLIENT_SECRET}
  redirect-uri: http://localhost:8080/oauth/github/callback
  token-uri: https://github.com/login/oauth/access_token
  user-uri: https://api.github.com/user
  api-url: https://api.github.com

gpt:
  api:
    feature-inference-url: http://localhost:8000/api/feature-inference
    generate-checklist-url: http://localhost:8000/api/generate-checklist

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: false

server:
  port: 8081